import { Tabnas } from '@tabnas/parser'
import { abnf } from '@tabnas/abnf'

const tn = new Tabnas({ plugins: [abnf] })

tn.abnf(`
  list  = item *( COMMA item )
  item  = 1*ALPHA
  COMMA = ","
`)

// `ALPHA` is an RFC 5234 core rule, pulled in because the grammar refers to it.
// `*( … )` is sugar: it desugars into generated rules you did not write, which
// is what to remember when attaching actions later.
const rules = Object.keys(tn.rule() as object)
console.log('ALPHA pulled in:', rules.includes('ALPHA'))
console.log('rules generated by desugaring:', rules.filter((n) => n.startsWith('_gen')).length)
