package main

import (
	"fmt"
	"strings"

	abnf "github.com/tabnas/abnf/go"
	tabnas "github.com/tabnas/parser/go"
)

func main() {
	j := tabnas.Make()

	_, err := abnf.Install(j, `
  list  = item *( COMMA item )
  item  = 1*ALPHA
  COMMA = ","
`, nil, nil)
	if err != nil {
		panic(err)
	}

	// `ALPHA` is an RFC 5234 core rule, pulled in because the grammar refers to
	// it. `*( … )` is sugar: it desugars into generated rules you did not write,
	// which is what to remember when attaching actions later.
	alpha, generated := false, 0
	for name := range j.RSM() {
		if "ALPHA" == name {
			alpha = true
		}
		if strings.HasPrefix(name, "_gen") {
			generated++
		}
	}
	fmt.Println("ALPHA pulled in:", alpha)
	fmt.Println("rules generated by desugaring:", generated)
}
