#!/usr/bin/env node
// gen-ax-data.mjs — regenerate src/data/ from sibling repo checkouts.
//
// The site must not hand-list facts another repo owns. Two of them cannot be
// imported from npm, so they are BUNDLED here as generated JSON, committed,
// and checked for staleness (`--check`, wired into `npm run check`):
//
//   ../parser/schema/error-codes.json  -> src/data/error-codes.json
//   ../skills/skills/<name>/SKILL.md   -> src/data/skills.json
//   ../skills/mcp.json                 -> src/data/skills.json (.mcp)
//
// Why bundled rather than imported:
//   - @tabnas/parser's npm package ships only LICENSE + dist, so schema/ is
//     not in it. The registry cannot serve the error catalogue.
//   - @tabnas/skills is not an npm package at all; it is an Agent Plugins
//     repository, and its skills are markdown with YAML frontmatter.
// When @tabnas/mcp publishes (it bundles the same schemas in its own data/),
// error-codes.json can become a plain dependency import and this half of the
// generator goes away.
//
// The fleet layout is sibling checkouts beside this repo: ../<repo>. Running
// it twice is byte-idempotent, and it never reaches the network.
//
// Usage:
//   node tools/gen-ax-data.mjs           # write src/data/*.json
//   node tools/gen-ax-data.mjs --check   # exit 1 if a file would change

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '..')
const FLEET = join(REPO, '..')
const DATA = join(REPO, 'src', 'data')

const CHECK = process.argv.includes('--check')

const problems = []
const notes = []

// --- the error registry -----------------------------------------------------

function errorCodes() {
  const src = join(FLEET, 'parser', 'schema', 'error-codes.json')
  if (!existsSync(src)) return null
  const raw = JSON.parse(readFileSync(src, 'utf8'))

  // Keep only what the site renders, and keep it sorted, so an unrelated
  // change to the generator's source cannot reorder the committed file.
  const codes = Object.keys(raw.codes || {})
    .sort()
    .map((code) => ({
      code,
      message: raw.codes[code].message ?? '',
      hint: raw.codes[code].hint ?? '',
    }))

  return {
    $comment:
      'GENERATED by tools/gen-ax-data.mjs from ../parser/schema/error-codes.json. Do not edit.',
    engine: raw.version ?? null,
    codes,
  }
}

// --- the plugin descriptors -------------------------------------------------

// Every plugin repo carries a generated tabnas.plugin.json (admin ADR-10).
// The engine registry above covers only the nine base codes; a plugin's own
// codes are declared in its descriptor, so the error reference needs both or
// it answers "unknown code" for most of what an agent will actually hit.
function plugins() {
  // Descriptors are looked for one AND two levels below the fleet root. Two,
  // because an aggregate checkout nests them (../tabnas/<repo>) — csv and xml
  // live only there in a normal layout, and xml alone declares 20 codes, so a
  // one-level scan silently drops the largest catalogue in the fleet.
  const dirs = []
  for (const a of readdirSync(FLEET, { withFileTypes: true })) {
    if (!a.isDirectory()) continue
    dirs.push([a.name, join(FLEET, a.name)])
    for (const b of readdirSync(join(FLEET, a.name), { withFileTypes: true })) {
      if (b.isDirectory() && b.name !== 'node_modules') {
        dirs.push([b.name, join(FLEET, a.name, b.name)])
      }
    }
  }

  const found = []
  for (const [repo, dir] of dirs) {
    const file = join(dir, 'tabnas.plugin.json')
    if (!existsSync(file)) continue
    let d
    try {
      d = JSON.parse(readFileSync(file, 'utf8'))
    } catch {
      problems.push(`${repo}/tabnas.plugin.json: not valid JSON`)
      continue
    }
    found.push({
      name: d.name,
      repo,
      description: d.description ?? '',
      base: d.base ?? null,
      extensions: d.extensions ?? [],
      errorCodes: Array.isArray(d.errorCodes) ? [...d.errorCodes].sort() : [],
      repository: d.repository ?? '',
    })
  }
  if (!found.length) return null

  // Deduplicate by package name (the same repo can appear at both levels) and
  // sort, so the committed file does not depend on readdir order.
  const byName = new Map()
  for (const p of found.sort((a, b) => a.repo.localeCompare(b.repo))) {
    if (!byName.has(p.name)) byName.set(p.name, p)
  }

  return {
    $comment:
      'GENERATED by tools/gen-ax-data.mjs from each ../<repo>/tabnas.plugin.json. Do not edit.',
    plugins: [...byName.values()].sort((a, b) => a.name.localeCompare(b.name)),
  }
}

// --- the skills catalogue ---------------------------------------------------

// A deliberately small YAML reader: Agent Skills frontmatter is a flat map of
// scalar values, and every key the site renders is a plain string. A folded
// block or a nested map would be silently mis-read, so anything that is not
// `key: value` on one line is reported rather than guessed at.
function frontmatter(text, where) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!m) {
    problems.push(`${where}: no YAML frontmatter`)
    return null
  }
  const out = {}
  for (const line of m[1].split(/\r?\n/)) {
    if (!line.trim() || line.trimStart().startsWith('#')) continue
    const kv = line.match(/^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/)
    if (!kv) {
      problems.push(`${where}: frontmatter line is not a simple key: value — ${line}`)
      continue
    }
    let value = kv[2].trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    out[kv[1]] = value
  }
  return out
}

// The description is one long sentence pair: what it does, then when to use
// it. The site shows the first as a summary and the second as the trigger,
// which is also how an agent reads it. Split on the documented "Use when"
// convention; if a skill ever stops following it, keep the whole thing as the
// summary rather than cutting it in an arbitrary place.
function splitDescription(description) {
  const i = description.search(/\bUse when\b/)
  if (i < 0) return { summary: description.trim(), useWhen: '' }
  return {
    summary: description.slice(0, i).trim(),
    useWhen: description.slice(i).trim(),
  }
}

function skills() {
  const root = join(FLEET, 'skills')
  if (!existsSync(root)) return null

  const dir = join(root, 'skills')
  const names = readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()

  const list = names.map((name) => {
    const file = join(dir, name, 'SKILL.md')
    const fm = frontmatter(readFileSync(file, 'utf8'), `skills/${name}/SKILL.md`) || {}
    // The standard requires frontmatter `name` to equal the directory name.
    // Reporting a mismatch is cheaper here than debugging a broken install.
    if (fm.name && fm.name !== name) {
      problems.push(`skills/${name}: frontmatter name is "${fm.name}", not the directory name`)
    }
    const references = existsSync(join(dir, name, 'references'))
      ? readdirSync(join(dir, name, 'references')).filter((f) => f.endsWith('.md')).sort()
      : []
    return {
      name,
      ...splitDescription(fm.description ?? ''),
      license: fm.license ?? '',
      compatibility: fm.compatibility ?? '',
      references,
    }
  })

  const plugin = JSON.parse(readFileSync(join(root, 'plugin.json'), 'utf8'))
  const mcp = JSON.parse(readFileSync(join(root, 'mcp.json'), 'utf8'))

  return {
    $comment: 'GENERATED by tools/gen-ax-data.mjs from ../skills. Do not edit.',
    plugin: {
      name: plugin.name,
      version: plugin.version,
      description: plugin.description,
      license: plugin.license,
    },
    // Rendered as the install snippet on /mcp, so it must stay verbatim: a
    // command the reader copies has to be the one the manifest declares.
    mcp: mcp.servers ?? {},
    skills: list,
  }
}

// --- write or check ---------------------------------------------------------

function emit(name, value) {
  const path = join(DATA, name)
  if (value == null) {
    notes.push(`${name}: sibling checkout missing — left as committed`)
    return
  }
  const next = JSON.stringify(value, null, 2) + '\n'
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null

  if (current === next) {
    notes.push(`${name}: up to date`)
    return
  }
  if (CHECK) {
    problems.push(`${name}: STALE — regenerate with \`node tools/gen-ax-data.mjs\``)
    return
  }
  mkdirSync(DATA, { recursive: true })
  writeFileSync(path, next)
  notes.push(`${name}: ${current === null ? 'created' : 'updated'}`)
}

emit('error-codes.json', errorCodes())
emit('plugins.json', plugins())
emit('skills.json', skills())

for (const note of notes) console.log(`  ${note}`)
if (problems.length) {
  for (const p of problems) console.error(`  ${p}`)
  process.exit(1)
}
