#!/usr/bin/env node
// gen-ax-data.mjs — regenerate src/data/ from sibling repo checkouts.
//
// The site must not hand-list facts another repo owns. Two of them cannot be
// imported from npm, so they are BUNDLED here as generated JSON, committed,
// and checked for staleness (`--check`, wired into `npm run check`):
//
//   ../parser/schema/error-codes.json  -> src/data/error-codes.json
//   ../skills/skills/<name>/SKILL.md   -> src/data/skills.json
//   ../skills/mcp.json                 -> src/data/skills.json (.mcp)
//   ../mcp/ts/src/tools.ts             -> src/data/mcp-tools.json
//
// Why bundled rather than imported:
//   - @tabnas/parser's npm package ships only LICENSE + dist, so schema/ is
//     not in it. The registry cannot serve the error catalogue.
//   - @tabnas/skills is not an npm package at all; it is an Agent Plugins
//     repository, and its skills are markdown with YAML frontmatter.
// When @tabnas/mcp publishes (it bundles the same schemas in its own data/),
// error-codes.json can become a plain dependency import and this half of the
// generator goes away.
//
// The fleet layout is sibling checkouts beside this repo: ../<repo>. Running
// it twice is byte-idempotent, and it never reaches the network.
//
// Usage:
//   node tools/gen-ax-data.mjs           # write src/data/*.json
//   node tools/gen-ax-data.mjs --check   # exit 1 if a file would change

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '..')
const FLEET = join(REPO, '..')
const DATA = join(REPO, 'src', 'data')

const CHECK = process.argv.includes('--check')

const problems = []
const notes = []

// --- the error registry -----------------------------------------------------

function errorCodes() {
  const src = join(FLEET, 'parser', 'schema', 'error-codes.json')
  if (!existsSync(src)) return null
  const raw = JSON.parse(readFileSync(src, 'utf8'))

  // Keep only what the site renders, and keep it sorted, so an unrelated
  // change to the generator's source cannot reorder the committed file.
  //
  // BOTH catalogues in the registry, not just `codes`. The engine also has a
  // `goOnly` block — today just `internal`, raised when the Go engine
  // recovers a panic from a plugin callback or matcher, with no TypeScript
  // counterpart. It was being dropped here, so an agent holding a real Go
  // diagnostic got nothing at /errors/internal. A code the fleet can raise
  // and the reference cannot explain is the exact gap this file exists to
  // close, so the runtime is carried through as a field rather than the code
  // being silently omitted.
  const pick = (code, entry, runtime) => ({
    code,
    message: entry.message ?? '',
    hint: entry.hint ?? '',
    runtime,
  })

  const codes = [
    ...Object.keys(raw.codes || {}).map((c) => pick(c, raw.codes[c], 'both')),
    ...Object.keys(raw.goOnly || {}).map((c) => pick(c, raw.goOnly[c], 'go')),
  ].sort((a, b) => a.code.localeCompare(b.code))

  return {
    $comment:
      'GENERATED by tools/gen-ax-data.mjs from ../parser/schema/error-codes.json. Do not edit.',
    engine: raw.version ?? null,
    codes,
  }
}

// --- the plugin descriptors -------------------------------------------------

// Every plugin repo carries a generated tabnas.plugin.json (admin ADR-10).
// The engine registry above covers only the nine base codes; a plugin's own
// codes are declared in its descriptor, so the error reference needs both or
// it answers "unknown code" for most of what an agent will actually hit.
function plugins() {
  // Descriptors are looked for one AND two levels below the fleet root. Two,
  // because an aggregate checkout nests them (../tabnas/<repo>) — csv and xml
  // live only there in a normal layout, and xml alone declares 20 codes, so a
  // one-level scan silently drops the largest catalogue in the fleet.
  const dirs = []
  for (const a of readdirSync(FLEET, { withFileTypes: true })) {
    if (!a.isDirectory()) continue
    dirs.push([a.name, join(FLEET, a.name)])
    for (const b of readdirSync(join(FLEET, a.name), { withFileTypes: true })) {
      if (b.isDirectory() && b.name !== 'node_modules') {
        dirs.push([b.name, join(FLEET, a.name, b.name)])
      }
    }
  }

  const found = []
  for (const [repo, dir] of dirs) {
    const file = join(dir, 'tabnas.plugin.json')
    if (!existsSync(file)) continue
    let d
    try {
      d = JSON.parse(readFileSync(file, 'utf8'))
    } catch {
      problems.push(`${repo}/tabnas.plugin.json: not valid JSON`)
      continue
    }
    found.push({
      name: d.name,
      repo,
      description: d.description ?? '',
      base: d.base ?? null,
      extensions: d.extensions ?? [],
      errorCodes: Array.isArray(d.errorCodes) ? [...d.errorCodes].sort() : [],
      // The uniform C ABI (ADR-12), when the repo carries one. Kept as its
      // own field and NEVER merged into errorCodes: these are call-level
      // codes from a shared library's JSON reply, not parse diagnostics, and
      // `internal` means something different in each. Flattening the two
      // namespaces would tell a reader that a failed FFI call and a recovered
      // plugin panic are the same event.
      clib: d.clib
        ? {
            library: d.clib.library ?? '',
            abi: d.clib.abi ?? '',
            errorCodes: Array.isArray(d.clib.errorCodes)
              ? [...d.clib.errorCodes].sort()
              : [],
          }
        : null,
      repository: d.repository ?? '',
    })
  }
  if (!found.length) return null

  // Deduplicate by package name (the same repo can appear at both levels) and
  // sort, so the committed file does not depend on readdir order.
  const byName = new Map()
  for (const p of found.sort((a, b) => a.repo.localeCompare(b.repo))) {
    if (!byName.has(p.name)) byName.set(p.name, p)
  }

  return {
    $comment:
      'GENERATED by tools/gen-ax-data.mjs from each ../<repo>/tabnas.plugin.json. Do not edit.',
    plugins: [...byName.values()].sort((a, b) => a.name.localeCompare(b.name)),
  }
}

// --- the skills catalogue ---------------------------------------------------

// A deliberately small YAML reader: Agent Skills frontmatter is a flat map of
// scalar values, and every key the site renders is a plain string. A folded
// block or a nested map would be silently mis-read, so anything that is not
// `key: value` on one line is reported rather than guessed at.
function frontmatter(text, where) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!m) {
    problems.push(`${where}: no YAML frontmatter`)
    return null
  }
  const out = {}
  for (const line of m[1].split(/\r?\n/)) {
    if (!line.trim() || line.trimStart().startsWith('#')) continue
    const kv = line.match(/^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/)
    if (!kv) {
      problems.push(`${where}: frontmatter line is not a simple key: value — ${line}`)
      continue
    }
    let value = kv[2].trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    out[kv[1]] = value
  }
  return out
}

// The description is one long sentence pair: what it does, then when to use
// it. The site shows the first as a summary and the second as the trigger,
// which is also how an agent reads it. Split on the documented "Use when"
// convention; if a skill ever stops following it, keep the whole thing as the
// summary rather than cutting it in an arbitrary place.
function splitDescription(description) {
  const i = description.search(/\bUse when\b/)
  if (i < 0) return { summary: description.trim(), useWhen: '' }
  return {
    summary: description.slice(0, i).trim(),
    useWhen: description.slice(i).trim(),
  }
}

function skills() {
  const root = join(FLEET, 'skills')
  if (!existsSync(root)) return null

  const dir = join(root, 'skills')
  const names = readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort()

  const list = names.map((name) => {
    const file = join(dir, name, 'SKILL.md')
    const text = readFileSync(file, 'utf8')
    const fm = frontmatter(text, `skills/${name}/SKILL.md`) || {}
    // The standard requires frontmatter `name` to equal the directory name.
    // Reporting a mismatch is cheaper here than debugging a broken install.
    if (fm.name && fm.name !== name) {
      problems.push(`skills/${name}: frontmatter name is "${fm.name}", not the directory name`)
    }
    const references = existsSync(join(dir, name, 'references'))
      ? readdirSync(join(dir, name, 'references')).filter((f) => f.endsWith('.md')).sort()
      : []
    // The skill's own section headings, in order — the outline /skills/<name>
    // shows so a reader can judge what the skill covers without this file
    // duplicating its body (the SKILL.md stays the one source). Fenced code
    // is stripped first so a `## ` inside an example cannot become a section.
    const sections = [
      ...text.replace(/^```.*$[\s\S]*?^```\s*$/gm, '').matchAll(/^## (.+)$/gm),
    ].map((m) => m[1].trim())
    return {
      name,
      ...splitDescription(fm.description ?? ''),
      license: fm.license ?? '',
      compatibility: fm.compatibility ?? '',
      references,
      sections,
    }
  })

  const plugin = JSON.parse(readFileSync(join(root, 'plugin.json'), 'utf8'))
  const mcp = JSON.parse(readFileSync(join(root, 'mcp.json'), 'utf8'))

  // Claude Code installs by <plugin>@<marketplace>, and the marketplace half
  // is declared by .claude-plugin/marketplace.json in the same repo. Read it
  // rather than typing it, so the install command the site renders cannot
  // drift from the claim the repo actually makes.
  const mpFile = join(root, '.claude-plugin', 'marketplace.json')
  const marketplace = existsSync(mpFile)
    ? JSON.parse(readFileSync(mpFile, 'utf8')).name ?? null
    : null

  return {
    $comment: 'GENERATED by tools/gen-ax-data.mjs from ../skills. Do not edit.',
    plugin: {
      name: plugin.name,
      version: plugin.version,
      description: plugin.description,
      license: plugin.license,
    },
    marketplace,
    // Rendered as the install snippet on /mcp, so it must stay verbatim: a
    // command the reader copies has to be the one the manifest declares.
    mcp: mcp.servers ?? {},
    skills: list,
  }
}

// --- the MCP tool set -------------------------------------------------------

// The names of the tools @tabnas/mcp actually exposes, read from the one
// place that decides them: ts/src/tools.ts in the mcp sibling.
//
// WHY THIS EXISTS. /mcp carried a hand-typed table of six tools. Phase 5
// added a seventh (`compare_grammars`) and the page was never updated, so
// the site advertised six tools for weeks while the server served seven —
// the heading, the lede and the meta description all wrong, and nothing
// anywhere to notice. Derive, never hand-maintain.
//
// Only the SET of names is generated. Each row's prose and its CLI
// equivalent are editorial and stay authored in mcp.astro; that page
// asserts its rows against this list at build time, so an added or removed
// tool fails the build instead of silently shipping.
function mcpTools() {
  const file = join(FLEET, 'mcp', 'ts', 'src', 'tools.ts')
  if (!existsSync(file)) return null

  const src = readFileSync(file, 'utf8')
  const from = src.indexOf('export const TOOLS = [')
  const to = src.indexOf('] as const', from)
  if (from < 0 || to < 0) {
    throw new Error('gen-ax-data: could not find the TOOLS array in ' + file)
  }

  // Scoped to the TOOLS slice on purpose: RESOURCES below it also has `name`
  // keys, and they are filenames, not tools.
  const names = [...src.slice(from, to).matchAll(/^\s*name: '([a-z_]+)',$/gm)]
    .map((m) => m[1])
  if (0 === names.length) {
    throw new Error('gen-ax-data: TOOLS array parsed to zero tools')
  }
  return { tools: names }
}

// --- write or check ---------------------------------------------------------

function emit(name, value) {
  const path = join(DATA, name)
  if (value == null) {
    notes.push(`${name}: sibling checkout missing — left as committed`)
    return
  }
  const next = JSON.stringify(value, null, 2) + '\n'
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null

  if (current === next) {
    notes.push(`${name}: up to date`)
    return
  }
  if (CHECK) {
    problems.push(`${name}: STALE — regenerate with \`node tools/gen-ax-data.mjs\``)
    return
  }
  mkdirSync(DATA, { recursive: true })
  writeFileSync(path, next)
  notes.push(`${name}: ${current === null ? 'created' : 'updated'}`)
}

emit('error-codes.json', errorCodes())
emit('plugins.json', plugins())
emit('skills.json', skills())
emit('mcp-tools.json', mcpTools())

for (const note of notes) console.log(`  ${note}`)
if (problems.length) {
  for (const p of problems) console.error(`  ${p}`)
  process.exit(1)
}
